# DNS настройки
no-resolv
server=127.0.0.1#5353
domain-needed
bogus-priv
cache-size=0

# Сетевые настройки
interface=br0
bind-dynamic
dhcp-authoritative

# DHCP диапазон для моста
dhcp-range=set:br0,192.168.100.10,192.168.100.99,255.255.255.0,12h

# Локальный домен
domain=lan,192.168.100.0/24
local=/lan/
expand-hosts

# Твики для Windows (чтобы быстрее получали IP)
dhcp-option=252,"\n"
dhcp-option=vendor:MSFT,2,1i
