# DNS настройки
no-resolv
server=127.0.0.1#5353
domain-needed
bogus-priv
cache-size=0

# Оба интерфейса слушают (wlan0 без IP, но DHCP работает!)
interface=usb0
interface=wlan0
bind-dynamic
dhcp-authoritative

# Единый DHCP диапазон
dhcp-range=192.168.100.10,192.168.100.99,255.255.255.0,12h

# Локальный домен
domain=lan,192.168.100.0/24
local=/lan/
expand-hosts

# Твики для Windows
dhcp-option=252,"\n"
dhcp-option=vendor:MSFT,2,1i
