#!/usr/sbin/nft -f

flush ruleset

table ip nat {
	chain prerouting {
		type nat hook prerouting priority -100;
		# DNS редирект для usb0
		iif "usb0" udp dport 53 redirect to :53
		iif "usb0" tcp dport 53 redirect to :53
		# DNS редирект для wlan0 (клиенты WiFi)
		iif "wlan0" udp dport 53 redirect to :53
		iif "wlan0" tcp dport 53 redirect to :53
	}

	chain postrouting {
		type nat hook postrouting priority 100;
		# NAT для всей подсети
		ip saddr 192.168.100.0/24 masquerade
	}
}
