#!/usr/sbin/nft -f

flush ruleset

table ip filter {
    chain forward {
        type filter hook forward priority 0;
        iif wlan0 oif usb0 accept
        iif usb0 oif wlan0 accept
    }
}

table ip nat {
    chain prerouting {
        type nat hook prerouting priority -100;
        iif "usb0" udp dport 53 redirect to :53
        iif "usb0" tcp dport 53 redirect to :53
        iif "wlan0" udp dport 53 redirect to :53
        iif "wlan0" tcp dport 53 redirect to :53
    }

    chain postrouting {
        type nat hook postrouting priority 100;
        ip saddr 192.168.100.0/24 masquerade
    }
}
