name: Build Env
on:
  push:
    paths: [ 'Dockerfile' ] # Сработает только при изменении списка пакетов
  workflow_dispatch:        # Позволит запустить сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Этот шаг создаст переменную env.IMAGE_NAME в нижнем регистре
      - name: Prepare image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/openstick-builder/build-env:latest" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Используем переменную, которую подготовили выше
          tags: ${{ env.IMAGE_NAME }}
