name: Build Env
on:
  push:
    paths: [ 'Dockerfile' ] # Сработает только при изменении списка пакетов
  workflow_dispatch:        # Позволит запустить сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Мы принудительно переводим название в нижний регистр
          tags:  ghcr.io/${{ github.repository_owner }}/openstick-builder/build-env:latest
